---

- name: Create bin directory
  file: path={{ansible_env.HOME}}/bin state=directory

- name: Create develop directory
  file: path={{ansible_env.HOME}}/develop state=directory

- name: Create .tmp directory
  file: path={{ansible_env.HOME}}/.cache/tmp state=directory

- name: Clone dot files
  git: repo=https://github.com/forkedjensh/dotfiles.git
       dest={{ ansible_env.HOME }}/dotfiles
  notify:
    - Prepare vim
    - Install vim plugins
    - Postprocess vim YCM
    - Get rst2ctags.py for vim tagbar

- name: Link dot files
  file: src={{item.value.src}} dest={{item.value.dest}}
  with_dict:
    vimrc:
      src: ~/dotfiles/_vimrc
      dest: ~/.vimrc
    zshrc:
      src: ~/dotfiles/_zshrc
      dest: ~/.zshrc
    tmuxconf:
      src: ~/dotfiles/_tmux.conf
      dest: ~/.tmux.conf
