---

- name: activate hombrew taps
  homebrew_tap: >
    tap={{ item }}
    state=present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"
