---

homebrew_taps:
  - caskroom/cask
  - homebrew/dupes
  - homebrew/science
  - homebrew/x11

homebrew_packages:
  - a2ps
  - adns
  - ansible
  - asciidoc
  - atk
  - atkmm
  - autoconf
  - autoconf-archive
  - autoenv
  - automake
  - bash-completion
  - bazaar
  - bdw-gc
  - berkeley-db
  - bmon
  - boost
  - boot2docker
  - byobu
  - c-ares
  - cairo
  - cairomm
  - cloog
  - cmake
  - confuse
  - coreutils
  - cscope
  - ctags
  - curl
  - czmq
  - d-bus
  - dblatex
  - dbus
  - ddrescue
  - dirmngr
  - docbook
  - docbook-xsl
  - docker
  - dos2unix
  - doxygen
  - dsh
  - duplicity
  - duply
  - emacs
  - expat
  - faac
  - fdk-aac
  - ffmpeg
  - flac
  - fondu
  - fontconfig
  - fontforge
  - freerdp
  - freetype
  - frei0r
  - fribidi
  - gcc
  - gd
  - gdbm
  - gdk-pixbuf
  - geoip
  - gettext
  - gfortran
  - ghostscript
  - git
  - git-annex
  - glib
  - glibmm
  - gmp
  - gmp@4
  - gnu-sed
  - gnupg
  - gnupg2
  - gnutls
  - gobject-introspection
  - gpg-agent
  - graphviz
  - gsasl
  - gsl
  - gtk+
  - gtkmm
  - gts
  - harfbuzz
  - hicolor-icon-theme
  - htop-osx
  - icu4c
  - inkscape
  - ircii
  - irssi
  - isl
  - isl@0.12
  - jasper
  - jbig2dec
  - jpeg
  - lame
  - leptonica
  - libass
  - libassuan
  - libcroco
  - libdshconfig
  - libdvdcss
  - libebml
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn
  - libksba
  - libmagic
  - libmatroska
  - libmpc
  - libogg
  - libpng
  - libquvi
  - librsvg
  - librsync
  - libsigc++
  - libsodium
  - libtasn1
  - libtiff
  - libtool
  - libunistring
  - libusb
  - libusb-compat
  - libvirt
  - libvo-aacenc
  - libvorbis
  - libvpx
  - libyaml
  - little-cms
  - little-cms2
  - lua
  - lzip
  - lzo
  - maven
  - media-info
  - mercurial
  - mkvtoolnix
  - mpfr
  - mysql
  - netcat
  - netpbm
  - nettle
  - newt
  - nmap
  - npth
  - opencore-amr
  - openjpeg
  - openldap
  - openssl
  - openssl@1.1
  - opus
  - orc
  - ossp-uuid
  - p11-kit
  - p7zip
  - pandoc
  - pango
  - pangomm
  - pcre
  - perl
  - pinentry
  - pinentry-mac
  - pixman
  - pkg-config
  - plantuml
  - popt
  - postgresql
  - pth
  - pwgen
  - py2cairo
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - pygobject
  - pygobject3
  - pygtk
  - pyqt
  - python
  - python3
  - qemu
  - qt
  - qt5
  - quvi
  - r
  - rdesktop
  - readline
  - rtmpdump
  - ruby
  - s-lang
  - schroedinger
  - sdl
  - shared-mime-info
  - shiboken
  - sip
  - sl
  - source-highlight
  - speex
  - sqlite
  - swig
  - tesseract
  - texi2html
  - texinfo
  - theora
  - tmux
  - tree
  - unpaper
  - utf8proc
  - vim
  - webp
  - wget
  - x264
  - xdot
  - xvid
  - xz
  - yajl
  - yasm
  - zeromq
  - zsh

homebrew_cask_packages:
  - adium
  - airmedia
  - amazon-music
  - apache-directory-studio
  - atom
  - avidemux
  - basictex
  - battle-net
  - chromium
  - citrix-receiver
  - cyberduck
  - dia
  - firefox
  - freecol
  - freemind
  - gimp
  - gog-galaxy
  - google-chrome
  - handbrake
  - handbrakebatch
  - hedgewars
  - inkscape
  - iterm2
  - java
  - keepassx
  - kodi
  - libreoffice
  - macvim
  - makemkv
  - minecraft
  - openttd
  - owncloud
  - projectlibre
  - scribus
  - scummvm
  - silverlight
  - soundflower
  - steam
  - subler
  - teamviewer
  - the-unarchiver
  - thunderbird
  - torbrowser
  - transmission
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - wireshark
  - xmind
  - xquartz
  - yed
  - yubikey-personalization-gui
