---

### BEGIN PREPARE VIM

- name: Prepare vim
  git: >
      repo=https://github.com/VundleVim/Vundle.vim.git
      dest={{ansible_env.HOME}}/.vim/bundle/Vundle.vim

- name: Install vim plugins
  command: vim +PluginInstall +qall

- name: Postprocess vim YCM
  command: >
    ./install.py
    chdir={{ansible_env.HOME}}/.vim/bundle/YouCompleteMe

- name: Get rst2ctags for vim tagbar
  get_url: >
      url=https://raw.githubusercontent.com/jszakmeister/rst2ctags/master/rst2ctags.py
      dest={{ansible_env.HOME}}/bin/rst2ctags.py
      mode="0644"

### END PREPARE VIM
