---

- name: Clone dot files
  git: repo=https://github.com/forkedjensh/dotfiles.git
       dest={{ ansible_env.HOME }}/dotfiles
- name: Link dot files
  file: src={{item.value.src}} dest={{item.value.dest}}
  with_dict:
    vimrc:
      src: ~/dotfiles/_vimrc
      dest: ~/.vimrc
    zshrc:
      src: ~/dotfiles/_zshrc
      dest: ~/.zshrc
    tmuxconf:
      src: ~/dotfiles/_tmux.conf
      dest: ~/.tmux.conf
